### ISSUE TITLE
Species pages "tabs" display

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/ala-mantine#1]
There are 2 minor differences between the Figma design and ala-mantine-demo implementations of the species page for the "tabs" layout.

1. The ala-mantine-demo version has a line-height of 25px for the tab (button) text, whereas the Figma design specifies 20px. This makes the tabs a little too tall, compared to the Figma version.
2. The tabs background-color is now white on the Figma design, whereas the demo has the same grey background-color as the top section of the page.

See screenshots:

![image](https://github.com/user-attachments/assets/77f94c2d-fb1a-4944-b09c-e8403b5cd576)
![image](https://github.com/user-attachments/assets/328d844b-a11a-4475-a0c8-49ca1ae7e107)

**Comment by nickdos** [comment]
I wasn't sure if these CSS rules were part of `ala-mantine` or part of the demo app, so feel free to move this.

**Comment by jack-brinkman** [comment]
@nickdos Just pushed a fix then (and related tabs background colour change to `ala-mantine-demo`)
